service: api-serverless

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: hotvenue

functions:
  test:
    handler: handler.test
    events:
      - http: get test
  api:
    handler: handler.api
    events:
      - http: get api
